### PR TITLE
update sample-app gitops to support both local and remote argocd depl…

### LINKED ISSUE #2: Sample app to support both local and remote Argocd deployment
Current sample app can support local Argocd deploy, but having issue to deploy the storage when using remote Argocd, need to support both.

### PR DESCRIPTION
**Pull request by huang-cn**
fixes #2 

…oyment (#2)

* dev3 update

* update ns

* update ns

* update url

* local cluster

* update ceph cluster

* robot-shop

* local kube cluster url

* update repo url

### CODE REVIEW

**Comment by huang-cn** [comment]
- Update sample app gitops to support both local and remote Argocd deployment, did not use ApplicationSet, instead, by simply removing the pre-defined argocd parent app definitions, the deployment parameters can be passed to the applications.  
- Quick correction in README to reflect deployment path change. more documentation update is still being working on.  
- Known issue, [sample app deploy to remote cluster issue when argocd CRDs are not exist](https://github.com/cloud-pak-gitops/sample-app-gitops/issues/6)

**Comment by morningspace** [comment]
This will drop the use of app-of-apps pattern completely, which is fine for now in our case. Can we create git issue in Argo community so that won't be lost as it seems really something should have been supported natively in Argo CD? On the other hand, didn't get the point why ApplicationSet doesn't help, is it because it does not support launching from UI? @huang-cn

**Comment by huang-cn** [comment]
@morningspace ApplicationSet could have helped if we can get it to work, but for now, I can only get it to work in local cluster, will need spend more time to investigate why ApplicationSet didn't work with remote cluster.   
But giving our current priority, by using the simpler app config, we can get the sample-app gitops to work, and also eliminate the need of manually updating the ApplicationSet Generator list every time when anyone need to use gitops to deploy sample-app.  right now it can work on both UI and Cli gitops deploy.

**Comment by gyliu513** [comment]
Need to open an issue in argocd to get some comments for why cascade parameters does not work for app of apps model.

**Pull request merged**
